# Generated by Django 6.0.2 on 2026-02-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origin_city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='origination',
            field=models.CharField(help_text='Full origination address (stored, not displayed in search)', max_length=128),
        ),
    ]
